#!/bin/bash
#
# Time-stamp: <Wednesday 2023-02-04 11:33:35 Jess Moore>

# ls
alias ll='ls -la -G'
alias lh='ls -lah -G'
alias lt='ls -laht -G'

# Git shortcuts
alias gsb='git status -sb'
alias gp='git push'
alias ga='git add'
alias gcmsg='git commit -m'
alias gt='git log --graph --abbrev-commit --decorate --oneline'

# pwd
alias makepwd='openssl rand -base64 6'
alias llast='ls -lt ~/Downloads |head -n 7'
alias grepnr='grep -nr'

# My scripts
# eg. ls myscripts
alias myscripts='ls ${HOME}/bin'
